name: Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
              npm ci
              npm run test:unit:coverage

      - name: Upload test coverage 🧪
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true

  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - run: |
              npm ci
              npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: master
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: docs