name: Tests

on:
  push:
    branches:
      - master

jobs:
  test-build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies 📦
        run: npm ci

      - name: Execute unit tests 🧪
        run: npm run test:unit:coverage

      - name: Upload test coverage 🧪
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: ./coverage/clover.xml
          flags: unittests
          name: codecov-umbrella
          verbose: true

      - name: Build Storybook 📕
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: storybook-deployment
          FOLDER: storybook-static
          CLEAN: true
          TARGET_FOLDER: docs