on:
    push:
        branches:
            - '**'

name: Coverage
jobs:
    publish-code-coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16'
                  cache: 'npm'
                  registry-url: https://registry.npmjs.org/
            - run: npm ci
            - name: Generate coverage report
              run: npm run test:unit:coverage
            - name: Deploy coverage report
              id: upload
              uses: cloudflare/pages-action@1
              with:
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  gitHubToken: ${{ secrets.GITHUB_TOKEN }}
                  projectName: mr-components-coverage
                  directory: coverage
                  branch: ${{ github.head_ref }}
            - name: Comment coverage on active PR
              run: |
                  echo "Upload ID: ${{ steps.upload.outputs.id }}"
                  echo "Upload Url: ${{ steps.upload.outputs.url }}"
